// ============================================================
// CONVETER — Central Tool Registry
// Every tool in the platform is registered here.
// The UI automatically builds from this registry.
// ============================================================

export type ToolCategory =
  | 'pdf'
  | 'image'
  | 'document'
  | 'data'
  | 'web'
  | 'video'
  | 'audio'
  | 'developer'
  | 'ai'
  | 'calculator'
  | 'business'
  | 'scanner'
  | 'archive'
  | 'security'
  | 'utilities';

export type ProcessingMode = 'local' | 'cloud' | 'hybrid';

export interface Tool {
  id: string;
  name: string;
  slug: string;
  category: ToolCategory;
  description: string;
  longDescription?: string;
  icon: string; // Lucide icon name
  tags: string[];
  supportedInputFormats?: string[];
  supportedOutputFormats?: string[];
  inputTypes: ('file' | 'text' | 'url' | 'camera' | 'clipboard')[];
  outputTypes: ('file' | 'text' | 'preview')[];
  processingMode: ProcessingMode;
  offlineSupported: boolean;
  onlineSupported: boolean;
  premium: boolean;
  batchSupported: boolean;
  workflowSupported: boolean;
  popular?: boolean;
  new?: boolean;
  status: 'stable' | 'beta' | 'coming-soon';
  relatedTools?: string[]; // tool slugs
}

export interface ToolCategory_Meta {
  id: ToolCategory;
  name: string;
  description: string;
  icon: string;
  color: string;
  bgClass: string;
}

// ============================================================
// CATEGORY METADATA
// ============================================================
export const CATEGORY_META: Record<ToolCategory, ToolCategory_Meta> = {
  pdf: {
    id: 'pdf',
    name: 'PDF Tools',
    description: 'Merge, split, compress, convert, edit and secure PDF files',
    icon: 'FileText',
    color: '#ef4444',
    bgClass: 'cat-pdf',
  },
  image: {
    id: 'image',
    name: 'Image Tools',
    description: 'Convert, compress, resize, edit and enhance images',
    icon: 'Image',
    color: '#f59e0b',
    bgClass: 'cat-image',
  },
  document: {
    id: 'document',
    name: 'Document Tools',
    description: 'Convert and process Word, RTF, EPUB, HTML documents',
    icon: 'FileEdit',
    color: '#3b82f6',
    bgClass: 'cat-document',
  },
  data: {
    id: 'data',
    name: 'Data & Spreadsheet',
    description: 'Convert, clean and analyze CSV, Excel, JSON, XML data',
    icon: 'Table',
    color: '#10b981',
    bgClass: 'cat-data',
  },
  web: {
    id: 'web',
    name: 'Web Tools',
    description: 'Scrape, convert and analyze web pages and content',
    icon: 'Globe',
    color: '#8b5cf6',
    bgClass: 'cat-web',
  },
  video: {
    id: 'video',
    name: 'Video Tools',
    description: 'Convert, compress, trim and process video files',
    icon: 'Video',
    color: '#ec4899',
    bgClass: 'cat-video',
  },
  audio: {
    id: 'audio',
    name: 'Audio Tools',
    description: 'Convert, compress, trim and process audio files',
    icon: 'Music',
    color: '#f97316',
    bgClass: 'cat-audio',
  },
  developer: {
    id: 'developer',
    name: 'Developer Tools',
    description: 'Format, validate, encode, decode and test developer utilities',
    icon: 'Code2',
    color: '#06b6d4',
    bgClass: 'cat-developer',
  },
  ai: {
    id: 'ai',
    name: 'AI Tools',
    description: 'Summarize, translate, extract and process with AI',
    icon: 'Sparkles',
    color: '#4A4AE8',
    bgClass: 'cat-ai',
  },
  calculator: {
    id: 'calculator',
    name: 'Calculators',
    description: 'Finance, engineering, unit conversion and general calculators',
    icon: 'Calculator',
    color: '#64748b',
    bgClass: 'cat-calculator',
  },
  business: {
    id: 'business',
    name: 'Business Tools',
    description: 'Invoices, quotations, resumes and professional templates',
    icon: 'Briefcase',
    color: '#16a34a',
    bgClass: 'cat-business',
  },
  scanner: {
    id: 'scanner',
    name: 'Scanner',
    description: 'Scan documents, IDs and receipts with your camera',
    icon: 'ScanLine',
    color: '#7c3aed',
    bgClass: 'cat-scanner',
  },
  archive: {
    id: 'archive',
    name: 'File & Archive',
    description: 'Compress, extract, rename and manage archives and files',
    icon: 'Archive',
    color: '#ca8a04',
    bgClass: 'cat-archive',
  },
  security: {
    id: 'security',
    name: 'Security & Privacy',
    description: 'Hashing, encryption, password generation and privacy tools',
    icon: 'Shield',
    color: '#dc2626',
    bgClass: 'cat-security',
  },
  utilities: {
    id: 'utilities',
    name: 'Utilities',
    description: 'QR codes, color tools, time utilities and clipboard tools',
    icon: 'Wrench',
    color: '#0891b2',
    bgClass: 'cat-utilities',
  },
};

// ============================================================
// TOOL REGISTRY
// ============================================================
export const TOOLS: Tool[] = [

  // ──────────────────────────────────────────────────────────
  // PDF TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'pdf-merge',
    name: 'Merge PDF',
    slug: 'merge-pdf',
    category: 'pdf',
    description: 'Combine multiple PDF files into one document',
    icon: 'FilePlus2',
    tags: ['merge', 'combine', 'join', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    status: 'stable',
    relatedTools: ['pdf-split', 'pdf-compress'],
  },
  {
    id: 'pdf-split',
    name: 'Split PDF',
    slug: 'split-pdf',
    category: 'pdf',
    description: 'Split a PDF into multiple files by pages or ranges',
    icon: 'Scissors',
    tags: ['split', 'separate', 'extract', 'pdf', 'pages'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    status: 'stable',
    relatedTools: ['pdf-merge', 'pdf-extract-pages'],
  },
  {
    id: 'pdf-compress',
    name: 'Compress PDF',
    slug: 'compress-pdf',
    category: 'pdf',
    description: 'Reduce PDF file size while maintaining quality',
    icon: 'Minimize2',
    tags: ['compress', 'reduce', 'size', 'optimize', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
    relatedTools: ['pdf-merge', 'pdf-repair'],
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    slug: 'jpg-to-pdf',
    category: 'pdf',
    description: 'Convert JPG images to PDF document',
    icon: 'ImagePlus',
    tags: ['jpg', 'jpeg', 'image', 'to', 'pdf', 'convert'],
    supportedInputFormats: ['jpg', 'jpeg'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    slug: 'pdf-to-jpg',
    category: 'pdf',
    description: 'Extract pages from PDF as JPG images',
    icon: 'FileImage',
    tags: ['pdf', 'to', 'jpg', 'image', 'extract', 'convert'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['jpg'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    slug: 'pdf-to-word',
    category: 'pdf',
    description: 'Convert PDF to editable Word document (DOCX)',
    icon: 'FileText',
    tags: ['pdf', 'to', 'word', 'docx', 'convert'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['docx'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    slug: 'word-to-pdf',
    category: 'pdf',
    description: 'Convert Word documents (DOC/DOCX) to PDF',
    icon: 'FileOutput',
    tags: ['word', 'docx', 'doc', 'to', 'pdf', 'convert'],
    supportedInputFormats: ['doc', 'docx'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'pdf-ocr',
    name: 'OCR PDF',
    slug: 'ocr-pdf',
    category: 'pdf',
    description: 'Extract text from scanned PDFs using OCR',
    icon: 'ScanText',
    tags: ['ocr', 'scan', 'text', 'extract', 'pdf', 'recognition'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf', 'txt'],
    inputTypes: ['file'],
    outputTypes: ['file', 'text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'pdf-protect',
    name: 'Protect PDF',
    slug: 'protect-pdf',
    category: 'pdf',
    description: 'Add password protection to PDF files',
    icon: 'Lock',
    tags: ['protect', 'password', 'encrypt', 'secure', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-unlock',
    name: 'Unlock PDF',
    slug: 'unlock-pdf',
    category: 'pdf',
    description: 'Remove password protection from PDF files',
    icon: 'Unlock',
    tags: ['unlock', 'remove', 'password', 'decrypt', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-watermark',
    name: 'Watermark PDF',
    slug: 'watermark-pdf',
    category: 'pdf',
    description: 'Add text or image watermarks to PDF pages',
    icon: 'Stamp',
    tags: ['watermark', 'stamp', 'text', 'branding', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-rotate',
    name: 'Rotate PDF',
    slug: 'rotate-pdf',
    category: 'pdf',
    description: 'Rotate PDF pages by 90°, 180° or 270°',
    icon: 'RotateCw',
    tags: ['rotate', 'orientation', 'pages', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-remove-pages',
    name: 'Remove PDF Pages',
    slug: 'remove-pdf-pages',
    category: 'pdf',
    description: 'Delete specific pages from a PDF document',
    icon: 'Trash2',
    tags: ['remove', 'delete', 'pages', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-extract-pages',
    name: 'Extract PDF Pages',
    slug: 'extract-pdf-pages',
    category: 'pdf',
    description: 'Extract specific pages from a PDF as a new file',
    icon: 'Copy',
    tags: ['extract', 'pages', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-reorder-pages',
    name: 'Reorder PDF Pages',
    slug: 'reorder-pdf-pages',
    category: 'pdf',
    description: 'Drag and drop to rearrange pages within a PDF',
    icon: 'GripVertical',
    tags: ['reorder', 'arrange', 'pages', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    slug: 'pdf-to-excel',
    category: 'pdf',
    description: 'Extract tables from PDF and convert to Excel',
    icon: 'Sheet',
    tags: ['pdf', 'to', 'excel', 'xlsx', 'table', 'convert'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['xlsx'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    slug: 'pdf-to-powerpoint',
    category: 'pdf',
    description: 'Convert PDF to editable PowerPoint presentation',
    icon: 'Monitor',
    tags: ['pdf', 'to', 'powerpoint', 'pptx', 'convert'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pptx'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-to-txt',
    name: 'PDF to Text',
    slug: 'pdf-to-text',
    category: 'pdf',
    description: 'Extract all text content from PDF files',
    icon: 'AlignLeft',
    tags: ['pdf', 'to', 'text', 'txt', 'extract'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['txt'],
    inputTypes: ['file'],
    outputTypes: ['file', 'text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    slug: 'pdf-to-markdown',
    category: 'pdf',
    description: 'Convert PDF content to clean Markdown format',
    icon: 'FileCode',
    tags: ['pdf', 'to', 'markdown', 'md', 'convert'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['md'],
    inputTypes: ['file'],
    outputTypes: ['file', 'text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    status: 'beta',
    new: true,
  },
  {
    id: 'pdf-sign',
    name: 'Sign PDF',
    slug: 'sign-pdf',
    category: 'pdf',
    description: 'Add digital signatures to PDF documents',
    icon: 'PenLine',
    tags: ['sign', 'signature', 'digital', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'pdf-redact',
    name: 'Redact PDF',
    slug: 'redact-pdf',
    category: 'pdf',
    description: 'Permanently remove sensitive information from PDFs',
    icon: 'EraserIcon',
    tags: ['redact', 'remove', 'sensitive', 'privacy', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-page-numbers',
    name: 'Add Page Numbers',
    slug: 'pdf-page-numbers',
    category: 'pdf',
    description: 'Add page numbers to PDF documents',
    icon: 'Hash',
    tags: ['page', 'numbers', 'header', 'footer', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-compare',
    name: 'Compare PDF',
    slug: 'compare-pdf',
    category: 'pdf',
    description: 'Compare two PDFs and highlight the differences',
    icon: 'GitCompare',
    tags: ['compare', 'diff', 'difference', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file', 'preview'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'pdf-repair',
    name: 'Repair PDF',
    slug: 'repair-pdf',
    category: 'pdf',
    description: 'Fix corrupted or damaged PDF files',
    icon: 'Wrench',
    tags: ['repair', 'fix', 'corrupt', 'damaged', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'ai-pdf-summarizer',
    name: 'AI PDF Summarizer',
    slug: 'ai-pdf-summarizer',
    category: 'pdf',
    description: 'Summarize PDF documents using AI',
    icon: 'Sparkles',
    tags: ['ai', 'summarize', 'summary', 'pdf'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['txt', 'md'],
    inputTypes: ['file'],
    outputTypes: ['text', 'file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    new: true,
    status: 'beta',
  },
  {
    id: 'ask-pdf',
    name: 'Ask PDF',
    slug: 'ask-pdf',
    category: 'pdf',
    description: 'Ask questions about your PDF and get AI answers',
    icon: 'MessageSquare',
    tags: ['ai', 'chat', 'ask', 'qa', 'questions', 'pdf'],
    supportedInputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: false,
    new: true,
    popular: true,
    status: 'beta',
  },

  // ──────────────────────────────────────────────────────────
  // IMAGE TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'image-converter',
    name: 'Image Converter',
    slug: 'image-converter',
    category: 'image',
    description: 'Convert images between JPG, PNG, WEBP, BMP, TIFF, GIF',
    icon: 'RefreshCw',
    tags: ['convert', 'image', 'jpg', 'png', 'webp', 'bmp', 'tiff', 'gif'],
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp', 'tiff', 'gif'],
    supportedOutputFormats: ['jpg', 'png', 'webp', 'bmp', 'tiff', 'gif'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    slug: 'image-compressor',
    category: 'image',
    description: 'Reduce image file size without visible quality loss',
    icon: 'Minimize2',
    tags: ['compress', 'reduce', 'optimize', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg', 'png', 'webp'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'image-resize',
    name: 'Image Resize',
    slug: 'image-resize',
    category: 'image',
    description: 'Resize images by dimensions or percentage',
    icon: 'Scaling',
    tags: ['resize', 'scale', 'dimension', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif'],
    supportedOutputFormats: ['jpg', 'png', 'webp'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'image-crop',
    name: 'Image Crop',
    slug: 'image-crop',
    category: 'image',
    description: 'Crop images to specific dimensions or aspect ratios',
    icon: 'Crop',
    tags: ['crop', 'trim', 'cut', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg', 'png', 'webp'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'background-remover',
    name: 'Background Remover',
    slug: 'background-remover',
    category: 'image',
    description: 'Automatically remove image backgrounds using AI',
    icon: 'Layers',
    tags: ['background', 'remove', 'transparent', 'ai', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['png'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'image-upscale',
    name: 'Image Upscaler',
    slug: 'image-upscaler',
    category: 'image',
    description: 'Enhance and upscale images up to 4x using AI',
    icon: 'ZoomIn',
    tags: ['upscale', 'enhance', 'ai', 'super-resolution', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg', 'png'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    new: true,
    status: 'beta',
  },
  {
    id: 'exif-viewer',
    name: 'EXIF Viewer',
    slug: 'exif-viewer',
    category: 'image',
    description: 'View all metadata and EXIF data from photos',
    icon: 'Info',
    tags: ['exif', 'metadata', 'info', 'gps', 'camera', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'tiff'],
    inputTypes: ['file'],
    outputTypes: ['preview', 'text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'exif-remover',
    name: 'EXIF Remover',
    slug: 'exif-remover',
    category: 'image',
    description: 'Strip all metadata from photos for privacy',
    icon: 'EraserIcon',
    tags: ['exif', 'metadata', 'remove', 'privacy', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'png'],
    supportedOutputFormats: ['jpg', 'png'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    slug: 'favicon-generator',
    category: 'image',
    description: 'Generate favicon files in all required sizes',
    icon: 'Bookmark',
    tags: ['favicon', 'icon', 'web', 'browser', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'svg'],
    supportedOutputFormats: ['ico', 'png'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'passport-photo',
    name: 'Passport Photo Maker',
    slug: 'passport-photo-maker',
    category: 'image',
    description: 'Create passport and ID photos in the correct dimensions',
    icon: 'UserSquare',
    tags: ['passport', 'id', 'photo', 'resize', 'image'],
    supportedInputFormats: ['jpg', 'jpeg', 'png'],
    supportedOutputFormats: ['jpg', 'png'],
    inputTypes: ['file', 'camera'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // DOCUMENT TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'docx-to-pdf',
    name: 'Word to PDF',
    slug: 'docx-to-pdf',
    category: 'document',
    description: 'Convert DOCX/DOC Word files to PDF',
    icon: 'FileOutput',
    tags: ['word', 'docx', 'to', 'pdf', 'convert'],
    supportedInputFormats: ['doc', 'docx', 'odt', 'rtf'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    slug: 'markdown-to-pdf',
    category: 'document',
    description: 'Convert Markdown files to beautifully formatted PDFs',
    icon: 'FileCode',
    tags: ['markdown', 'md', 'to', 'pdf', 'convert'],
    supportedInputFormats: ['md', 'markdown'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file', 'text'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'epub-to-pdf',
    name: 'EPUB to PDF',
    slug: 'epub-to-pdf',
    category: 'document',
    description: 'Convert EPUB eBooks to PDF format',
    icon: 'BookOpen',
    tags: ['epub', 'ebook', 'to', 'pdf', 'convert'],
    supportedInputFormats: ['epub'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    slug: 'html-to-pdf',
    category: 'document',
    description: 'Convert HTML files to PDF documents',
    icon: 'Globe',
    tags: ['html', 'to', 'pdf', 'convert', 'web'],
    supportedInputFormats: ['html', 'htm'],
    supportedOutputFormats: ['pdf'],
    inputTypes: ['file', 'text', 'url'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // DATA TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'csv-to-excel',
    name: 'CSV to Excel',
    slug: 'csv-to-excel',
    category: 'data',
    description: 'Convert CSV files to Excel spreadsheets',
    icon: 'Table2',
    tags: ['csv', 'to', 'excel', 'xlsx', 'convert'],
    supportedInputFormats: ['csv', 'tsv'],
    supportedOutputFormats: ['xlsx'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'excel-to-csv',
    name: 'Excel to CSV',
    slug: 'excel-to-csv',
    category: 'data',
    description: 'Convert Excel spreadsheets to CSV format',
    icon: 'Table',
    tags: ['excel', 'xlsx', 'to', 'csv', 'convert'],
    supportedInputFormats: ['xlsx', 'xls'],
    supportedOutputFormats: ['csv'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    slug: 'json-to-csv',
    category: 'data',
    description: 'Convert JSON data to CSV format',
    icon: 'Braces',
    tags: ['json', 'to', 'csv', 'convert', 'data'],
    supportedInputFormats: ['json'],
    supportedOutputFormats: ['csv'],
    inputTypes: ['file', 'text'],
    outputTypes: ['file', 'text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'json-to-excel',
    name: 'JSON to Excel',
    slug: 'json-to-excel',
    category: 'data',
    description: 'Convert JSON arrays/objects to Excel spreadsheets',
    icon: 'Table2',
    tags: ['json', 'to', 'excel', 'xlsx', 'convert', 'data'],
    supportedInputFormats: ['json'],
    supportedOutputFormats: ['xlsx'],
    inputTypes: ['file', 'text'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    slug: 'xml-to-json',
    category: 'data',
    description: 'Convert XML documents to JSON format',
    icon: 'Code',
    tags: ['xml', 'to', 'json', 'convert', 'data'],
    supportedInputFormats: ['xml'],
    supportedOutputFormats: ['json'],
    inputTypes: ['file', 'text'],
    outputTypes: ['file', 'text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'pdf-table-extractor',
    name: 'PDF Table Extractor',
    slug: 'pdf-table-extractor',
    category: 'data',
    description: 'Extract tables from PDFs to Excel or CSV',
    icon: 'TableProperties',
    tags: ['pdf', 'table', 'extract', 'excel', 'csv', 'data'],
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['xlsx', 'csv'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // WEB TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'url-scraper',
    name: 'URL Scraper',
    slug: 'url-scraper',
    category: 'web',
    description: 'Scrape content from public web pages responsibly',
    icon: 'Globe',
    tags: ['scrape', 'extract', 'url', 'web', 'page'],
    inputTypes: ['url'],
    outputTypes: ['file', 'text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'webpage-to-pdf',
    name: 'Webpage to PDF',
    slug: 'webpage-to-pdf',
    category: 'web',
    description: 'Convert any public URL to a PDF document',
    icon: 'FileOutput',
    tags: ['webpage', 'url', 'to', 'pdf', 'convert'],
    inputTypes: ['url'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'webpage-to-markdown',
    name: 'Webpage to Markdown',
    slug: 'webpage-to-markdown',
    category: 'web',
    description: 'Convert webpage content to clean Markdown',
    icon: 'FileCode',
    tags: ['webpage', 'url', 'to', 'markdown', 'md', 'convert'],
    inputTypes: ['url'],
    outputTypes: ['file', 'text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'table-scraper',
    name: 'Table Scraper',
    slug: 'table-scraper',
    category: 'web',
    description: 'Extract HTML tables from web pages as CSV or Excel',
    icon: 'Table',
    tags: ['table', 'scrape', 'extract', 'url', 'csv', 'excel'],
    inputTypes: ['url'],
    outputTypes: ['file', 'text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },
  {
    id: 'seo-analyzer',
    name: 'SEO Analyzer',
    slug: 'seo-analyzer',
    category: 'web',
    description: 'Analyze on-page SEO factors for any URL',
    icon: 'TrendingUp',
    tags: ['seo', 'analyze', 'meta', 'url', 'web'],
    inputTypes: ['url'],
    outputTypes: ['preview'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // DEVELOPER TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    category: 'developer',
    description: 'Format, validate and minify JSON',
    icon: 'Braces',
    tags: ['json', 'format', 'validate', 'beautify', 'developer'],
    inputTypes: ['text', 'file'],
    outputTypes: ['text', 'file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    slug: 'base64-encoder',
    category: 'developer',
    description: 'Encode and decode text and files in Base64',
    icon: 'Code2',
    tags: ['base64', 'encode', 'decode', 'developer'],
    inputTypes: ['text', 'file'],
    outputTypes: ['text', 'file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    slug: 'regex-tester',
    category: 'developer',
    description: 'Test and debug regular expressions with live preview',
    icon: 'Search',
    tags: ['regex', 'regular expression', 'test', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    slug: 'diff-checker',
    category: 'developer',
    description: 'Compare two texts and highlight the differences',
    icon: 'GitCompare',
    tags: ['diff', 'compare', 'text', 'changes', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    slug: 'jwt-decoder',
    category: 'developer',
    description: 'Decode and inspect JWT tokens',
    icon: 'KeyRound',
    tags: ['jwt', 'token', 'decode', 'developer', 'auth'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    slug: 'uuid-generator',
    category: 'developer',
    description: 'Generate UUID v1, v4, and v5 identifiers',
    icon: 'Hash',
    tags: ['uuid', 'guid', 'generate', 'random', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    slug: 'url-encoder',
    category: 'developer',
    description: 'Encode and decode URLs and query parameters',
    icon: 'Link',
    tags: ['url', 'encode', 'decode', 'uri', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    slug: 'color-converter',
    category: 'developer',
    description: 'Convert between HEX, RGB, HSL, and other color formats',
    icon: 'Palette',
    tags: ['color', 'hex', 'rgb', 'hsl', 'convert', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['text', 'preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'password-generator-dev',
    name: 'Password Generator',
    slug: 'password-generator',
    category: 'developer',
    description: 'Generate secure random passwords with custom options',
    icon: 'KeyRound',
    tags: ['password', 'generate', 'random', 'secure', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    slug: 'cron-generator',
    category: 'developer',
    description: 'Build and validate cron expressions visually',
    icon: 'Clock',
    tags: ['cron', 'schedule', 'expression', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    slug: 'sql-formatter',
    category: 'developer',
    description: 'Format and beautify SQL queries',
    icon: 'Database',
    tags: ['sql', 'format', 'query', 'beautify', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    slug: 'markdown-preview',
    category: 'developer',
    description: 'Write and preview Markdown with live rendering',
    icon: 'FileText',
    tags: ['markdown', 'preview', 'render', 'developer'],
    inputTypes: ['text', 'file'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    slug: 'lorem-ipsum',
    category: 'developer',
    description: 'Generate Lorem Ipsum placeholder text',
    icon: 'AlignLeft',
    tags: ['lorem', 'ipsum', 'placeholder', 'text', 'developer'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // CALCULATORS
  // ──────────────────────────────────────────────────────────
  {
    id: 'emi-calculator',
    name: 'EMI Calculator',
    slug: 'emi-calculator',
    category: 'calculator',
    description: 'Calculate monthly EMI for loans with amortization schedule',
    icon: 'IndianRupee',
    tags: ['emi', 'loan', 'finance', 'calculator', 'monthly'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    slug: 'percentage-calculator',
    category: 'calculator',
    description: 'Calculate percentages, increases, decreases and ratios',
    icon: 'Percent',
    tags: ['percentage', 'percent', 'ratio', 'calculator'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    slug: 'bmi-calculator',
    category: 'calculator',
    description: 'Calculate Body Mass Index (BMI)',
    icon: 'Activity',
    tags: ['bmi', 'body', 'mass', 'index', 'health', 'calculator'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    slug: 'age-calculator',
    category: 'calculator',
    description: 'Calculate exact age from date of birth',
    icon: 'Calendar',
    tags: ['age', 'birthday', 'date', 'calculator'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'gst-calculator',
    name: 'GST Calculator',
    slug: 'gst-calculator',
    category: 'calculator',
    description: 'Calculate GST inclusive and exclusive amounts',
    icon: 'Receipt',
    tags: ['gst', 'tax', 'finance', 'india', 'calculator'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    slug: 'unit-converter',
    category: 'calculator',
    description: 'Convert between length, weight, temperature and more',
    icon: 'ArrowLeftRight',
    tags: ['unit', 'convert', 'length', 'weight', 'temperature', 'calculator'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'sip-calculator',
    name: 'SIP Calculator',
    slug: 'sip-calculator',
    category: 'calculator',
    description: 'Calculate returns on systematic investment plans',
    icon: 'TrendingUp',
    tags: ['sip', 'investment', 'finance', 'returns', 'calculator'],
    inputTypes: ['text'],
    outputTypes: ['preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // AI TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'ai-summarizer',
    name: 'AI Document Summarizer',
    slug: 'ai-document-summarizer',
    category: 'ai',
    description: 'Summarize any document with AI in seconds',
    icon: 'Sparkles',
    tags: ['ai', 'summarize', 'document', 'text'],
    supportedInputFormats: ['pdf', 'docx', 'txt', 'md'],
    inputTypes: ['file', 'text'],
    outputTypes: ['text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    new: true,
    status: 'beta',
  },
  {
    id: 'ai-translator',
    name: 'AI Translation',
    slug: 'ai-translation',
    category: 'ai',
    description: 'Translate documents and text into 100+ languages',
    icon: 'Languages',
    tags: ['translate', 'language', 'ai', 'text', 'document'],
    inputTypes: ['file', 'text'],
    outputTypes: ['text', 'file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    new: true,
    status: 'beta',
  },
  {
    id: 'grammar-checker',
    name: 'Grammar Checker',
    slug: 'grammar-checker',
    category: 'ai',
    description: 'Check and correct grammar errors with AI',
    icon: 'CheckSquare',
    tags: ['grammar', 'spell', 'check', 'ai', 'text'],
    inputTypes: ['text'],
    outputTypes: ['text', 'preview'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'beta',
  },
  {
    id: 'paraphraser',
    name: 'AI Paraphraser',
    slug: 'ai-paraphraser',
    category: 'ai',
    description: 'Rewrite text in different tones and styles',
    icon: 'PenSquare',
    tags: ['paraphrase', 'rewrite', 'ai', 'text'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: false,
    status: 'beta',
  },
  {
    id: 'keyword-extractor',
    name: 'Keyword Extractor',
    slug: 'keyword-extractor',
    category: 'ai',
    description: 'Extract key terms and topics from any text',
    icon: 'Tags',
    tags: ['keyword', 'extract', 'topic', 'ai', 'text'],
    inputTypes: ['text', 'file'],
    outputTypes: ['text'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'beta',
  },

  // ──────────────────────────────────────────────────────────
  // SECURITY TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    slug: 'hash-generator',
    category: 'security',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes',
    icon: 'Hash',
    tags: ['hash', 'md5', 'sha256', 'sha512', 'security'],
    inputTypes: ['text', 'file'],
    outputTypes: ['text'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    slug: 'qr-generator',
    category: 'utilities',
    description: 'Generate QR codes for URLs, text, and more',
    icon: 'QrCode',
    tags: ['qr', 'code', 'generate', 'url', 'utilities'],
    inputTypes: ['text'],
    outputTypes: ['file', 'preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // VIDEO TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'video-converter',
    name: 'Video Converter',
    slug: 'video-converter',
    category: 'video',
    description: 'Convert videos between MP4, MOV, MKV, AVI, WEBM',
    icon: 'Video',
    tags: ['video', 'convert', 'mp4', 'mov', 'mkv', 'webm'],
    supportedInputFormats: ['mp4', 'mov', 'mkv', 'avi', 'webm'],
    supportedOutputFormats: ['mp4', 'mov', 'mkv', 'webm'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'video-compress',
    name: 'Video Compressor',
    slug: 'video-compressor',
    category: 'video',
    description: 'Reduce video file size for web and storage',
    icon: 'Minimize2',
    tags: ['video', 'compress', 'reduce', 'size'],
    supportedInputFormats: ['mp4', 'mov', 'mkv', 'avi'],
    supportedOutputFormats: ['mp4'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    slug: 'video-to-gif',
    category: 'video',
    description: 'Convert video clips to animated GIF files',
    icon: 'PlaySquare',
    tags: ['video', 'to', 'gif', 'animate', 'convert'],
    supportedInputFormats: ['mp4', 'mov', 'webm'],
    supportedOutputFormats: ['gif'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'video-to-audio',
    name: 'Video to Audio',
    slug: 'video-to-audio',
    category: 'video',
    description: 'Extract audio track from video files',
    icon: 'Music',
    tags: ['video', 'to', 'audio', 'mp3', 'extract'],
    supportedInputFormats: ['mp4', 'mov', 'mkv', 'avi', 'webm'],
    supportedOutputFormats: ['mp3', 'wav', 'aac'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // AUDIO TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'audio-converter',
    name: 'Audio Converter',
    slug: 'audio-converter',
    category: 'audio',
    description: 'Convert audio between MP3, WAV, AAC, M4A, FLAC',
    icon: 'Music',
    tags: ['audio', 'convert', 'mp3', 'wav', 'flac', 'aac'],
    supportedInputFormats: ['mp3', 'wav', 'aac', 'm4a', 'flac'],
    supportedOutputFormats: ['mp3', 'wav', 'aac', 'm4a', 'flac'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'speech-to-text',
    name: 'Speech to Text',
    slug: 'speech-to-text',
    category: 'audio',
    description: 'Transcribe audio and video files to text with AI',
    icon: 'Mic',
    tags: ['speech', 'text', 'transcribe', 'ai', 'audio'],
    supportedInputFormats: ['mp3', 'wav', 'aac', 'm4a'],
    outputTypes: ['text', 'file'],
    inputTypes: ['file'],
    processingMode: 'cloud',
    offlineSupported: false,
    onlineSupported: true,
    premium: true,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    new: true,
    status: 'beta',
  },

  // ──────────────────────────────────────────────────────────
  // BUSINESS TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    slug: 'invoice-generator',
    category: 'business',
    description: 'Create professional invoices and export as PDF',
    icon: 'FileSpreadsheet',
    tags: ['invoice', 'billing', 'business', 'pdf'],
    inputTypes: ['text'],
    outputTypes: ['file', 'preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'resume-builder',
    name: 'Resume / CV Builder',
    slug: 'resume-builder',
    category: 'business',
    description: 'Build professional resumes and export as PDF',
    icon: 'User',
    tags: ['resume', 'cv', 'job', 'business', 'pdf'],
    inputTypes: ['text'],
    outputTypes: ['file', 'preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
  {
    id: 'qr-business-card',
    name: 'Business Card Generator',
    slug: 'business-card-generator',
    category: 'business',
    description: 'Design digital and printable business cards',
    icon: 'CreditCard',
    tags: ['business', 'card', 'contact', 'design'],
    inputTypes: ['text'],
    outputTypes: ['file', 'preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // ARCHIVE TOOLS
  // ──────────────────────────────────────────────────────────
  {
    id: 'zip-compress',
    name: 'ZIP Compressor',
    slug: 'zip-compressor',
    category: 'archive',
    description: 'Create ZIP archives from multiple files',
    icon: 'Archive',
    tags: ['zip', 'compress', 'archive', 'files'],
    supportedInputFormats: ['*'],
    supportedOutputFormats: ['zip'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'zip-extract',
    name: 'ZIP Extractor',
    slug: 'zip-extractor',
    category: 'archive',
    description: 'Extract files from ZIP, 7Z, TAR, GZIP archives',
    icon: 'PackageOpen',
    tags: ['zip', 'extract', 'archive', '7z', 'tar', 'gzip'],
    supportedInputFormats: ['zip', '7z', 'tar', 'gz'],
    supportedOutputFormats: ['*'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: true,
    popular: true,
    status: 'stable',
  },
  {
    id: 'batch-rename',
    name: 'Batch Rename',
    slug: 'batch-rename',
    category: 'archive',
    description: 'Rename multiple files with patterns and rules',
    icon: 'FolderEdit',
    tags: ['rename', 'batch', 'files', 'pattern'],
    inputTypes: ['file'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: true,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // SCANNER
  // ──────────────────────────────────────────────────────────
  {
    id: 'document-scanner',
    name: 'Document Scanner',
    slug: 'document-scanner',
    category: 'scanner',
    description: 'Scan documents with your camera and export as PDF',
    icon: 'ScanLine',
    tags: ['scan', 'camera', 'document', 'pdf', 'ocr'],
    supportedInputFormats: ['jpg', 'jpeg', 'png'],
    supportedOutputFormats: ['pdf', 'jpg'],
    inputTypes: ['file', 'camera'],
    outputTypes: ['file'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: true,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },

  // ──────────────────────────────────────────────────────────
  // UTILITIES
  // ──────────────────────────────────────────────────────────
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    slug: 'timestamp-converter',
    category: 'utilities',
    description: 'Convert between Unix timestamps and human dates',
    icon: 'Clock',
    tags: ['timestamp', 'unix', 'date', 'time', 'convert', 'utilities'],
    inputTypes: ['text'],
    outputTypes: ['text', 'preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    status: 'stable',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    slug: 'color-picker',
    category: 'utilities',
    description: 'Pick colors and get HEX, RGB, HSL values',
    icon: 'Pipette',
    tags: ['color', 'pick', 'hex', 'rgb', 'hsl', 'utilities'],
    inputTypes: ['text'],
    outputTypes: ['text', 'preview'],
    processingMode: 'local',
    offlineSupported: true,
    onlineSupported: true,
    premium: false,
    batchSupported: false,
    workflowSupported: false,
    popular: true,
    status: 'stable',
  },
];

// ============================================================
// REGISTRY ACCESSORS
// ============================================================

/** Get all tools */
export const getAllTools = (): Tool[] => TOOLS;

/** Get tools by category */
export const getToolsByCategory = (category: ToolCategory): Tool[] =>
  TOOLS.filter((t) => t.category === category);

/** Get a tool by slug */
export const getToolBySlug = (slug: string): Tool | undefined =>
  TOOLS.find((t) => t.slug === slug);

/** Get a tool by id */
export const getToolById = (id: string): Tool | undefined =>
  TOOLS.find((t) => t.id === id);

/** Get popular tools */
export const getPopularTools = (limit = 12): Tool[] =>
  TOOLS.filter((t) => t.popular).slice(0, limit);

/** Get new tools */
export const getNewTools = (limit = 8): Tool[] =>
  TOOLS.filter((t) => t.new).slice(0, limit);

/** Search tools */
export const searchTools = (query: string): Tool[] => {
  if (!query.trim()) return TOOLS;
  const q = query.toLowerCase();
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q)) ||
      t.category.includes(q) ||
      t.supportedInputFormats?.some((f) => f.includes(q)) ||
      t.supportedOutputFormats?.some((f) => f.includes(q))
  );
};

/** Get tools grouped by category */
export const getToolsGroupedByCategory = (): Record<ToolCategory, Tool[]> => {
  return TOOLS.reduce(
    (acc, tool) => {
      if (!acc[tool.category]) acc[tool.category] = [];
      acc[tool.category].push(tool);
      return acc;
    },
    {} as Record<ToolCategory, Tool[]>
  );
};

/** Get related tools for a given tool */
export const getRelatedTools = (tool: Tool): Tool[] => {
  if (!tool.relatedTools?.length) {
    // fallback: same category
    return getToolsByCategory(tool.category)
      .filter((t) => t.id !== tool.id)
      .slice(0, 4);
  }
  return tool.relatedTools
    .map((slug) => getToolBySlug(slug))
    .filter(Boolean) as Tool[];
};
